### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by Leepoet** [synlp/R2GenRL#5]
How to fix it when using pycocoeval in your code? It is all good when I run R2GenCMN's code.

```
Traceback (most recent call last):
  File "/data/R2GenRL/modules/metrics.py", line 26, in compute_scores
    score, scores = scorer.compute_score(gts, res, verbose=0)
TypeError: compute_score() got an unexpected keyword argument 'verbose'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_rl.py", line 146, in <module>
    main()
  File "train_rl.py", line 142, in main
    trainer.train()
  File "/dataR2GenRL/modules/trainer_rl.py", line 65, in train
    result = self._train_epoch(epoch)
  File "/data/R2GenRL/modules/trainer_rl.py", line 331, in _train_epoch
    val_met = self.metric_ftns({i: [gt] for i, gt in enumerate(val_gts)},
  File "/data/R2GenRL/modules/metrics.py", line 28, in compute_scores
    score, scores = scorer.compute_score(gts, res)
  File "/data/R2GenRL/pycocoevalcap/meteor/meteor.py", line 43, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "/data/R2GenRL/pycocoevalcap/meteor/meteor.py", line 61, in _stat
    self.meteor_p.stdin.write('{}\n'.format(score_line))
BrokenPipeError: [Errno 32] Broken pipe
```

BTW, I have made sure that I install java.
```
java version "21.0.3" 2024-04-16 LTS
Java(TM) SE Runtime Environment (build 21.0.3+7-LTS-152)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.3+7-LTS-152, mixed mode, sharing)
```

**Comment by Andyfever123** [comment]
我也遇到了这个问题，请问您解决了吗？可以和我分享下您的解决方法吗？

**Comment by Junyiliu0** [comment]
你把他们组R2GenCMN对应的这个计算指标的文件夹复制到这个project里面就行。
